### ISSUE TITLE
What about Twitter?

### ISSUE THREAD

**Issue by sepulworld** [charlesrt/be-a-deletist#1]
Why is Twitter left out? :)

**Comment by jdwallace12** [comment]
ha was wondering the same thing

**Comment by charlesrt** [comment]
On the list 😉

Mostly, because I'm sticking with Twitter for now as I still get value from it. I need to go through the process of creating a dummy account just to delete it so I know I've got all the steps covered. 

Coming soon.

**Comment by charlesrt** [comment]
[Twitter now added](https://deletist.xyz/twitter)
